chunking_strategy: fixed
chunk_token_size: 128
chunk_token_overlap: 48
embedding_model: intfloat/multilingual-e5-large-instruct
index_type: vector_only
top_k: 16
hybrid_alpha: 0.5
bm25_vector_fusion: alpha
long_context_reorder: true
passage_compressor: none
reranker: cross-encoder/ms-marco-MiniLM-L-6-v2
reranker_top_n: 7
query_expansion: query_decompose
compressor_llm: null
expander_llm: azure/gpt-4o-mini
generator_llm: bedrock/openai.gpt-oss-20b-1:0
temperature: 1.0
reasoning: false
