chunking_strategy: recursive
chunk_token_size: 512
chunk_token_overlap: 0
embedding_model: intfloat/multilingual-e5-large-instruct
index_type: hybrid_bm25_vector
top_k: 18
hybrid_alpha: 0.613959729754525
bm25_vector_fusion: alpha
long_context_reorder: false
passage_compressor: none
reranker: Alibaba-NLP/gte-reranker-modernbert-base
reranker_top_n: 7
query_expansion: none
compressor_llm: null
expander_llm: null
generator_llm: azure/gpt-5-mini
temperature: 1.0
reasoning: true
