chunking_strategy: recursive
chunk_token_size: 256
chunk_token_overlap: 0
embedding_model: intfloat/e5-large-v2
index_type: vector_only
top_k: 20
hybrid_alpha: 0.5
bm25_vector_fusion: alpha
long_context_reorder: false
passage_compressor: none
reranker: none
reranker_top_n: 3
query_expansion: multi_query
compressor_llm: null
expander_llm: azure/gpt-4o-mini
generator_llm: azure/o4-mini
temperature: 1.0
reasoning: true
