chunking_strategy: fixed
chunk_token_size: 128
chunk_token_overlap: 0
embedding_model: sentence-transformers/all-MiniLM-L6-v2
index_type: hybrid_bm25_vector
top_k: 5
hybrid_alpha: 0.5
bm25_vector_fusion: rrf
long_context_reorder: false
passage_compressor: none
reranker: BAAI/bge-reranker-v2-m3
reranker_top_n: 5
query_expansion: hyde
compressor_llm: null
expander_llm: azure/gpt-4o-mini
generator_llm: bedrock/us.meta.llama4-maverick-17b-instruct-v1:0
temperature: 1.0
reasoning: false
